# General Import
spring.config.import=optional:file:.env[.properties]

server.port=${SERVICE_PORT:8080}

# Application name
spring.application.name=igrp-access-management
eureka.client.enabled=${EUREKA_CLIENT_ENABLED:false}
spring.cloud.discovery.enabled=${SPRING_CLOUD_DISCOVERY_ENABLED:false}

spring.cloud.refresh.enabled=false
spring.autoconfigure.exclude=org.springframework.cloud.autoconfigure.RefreshAutoConfiguration

springdoc.swagger-ui.docExpansion=none

# Datasource
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DATABASE:postgres}}
spring.datasource.username=${DATABASE_USERNAME:${POSTGRES_USER:postgres}}
spring.datasource.password=${DATABASE_PASSWORD:${POSTGRES_PASSWORD:postgres}}
spring.datasource.driver-class-name=org.postgresql.Driver

# Security
spring.security.oauth2.resourceserver.jwt.issuer-uri=${AUTH_JWT_ISSUER}

# Documentation
springdoc.swagger-ui.enabled=${ENABLE_SWAGGER:true}
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.showExtensions=true

# Storage
igrp.storage-provider=${IGRP_STORAGE_PROVIDER:minio}
igrp.minio.endpoint=${IGRP_STORAGE_ENDPOINT}
igrp.minio.port=${IGRP_STORAGE_PORT}
igrp.minio.security=${IGRP_STORAGE_SECURITY}
igrp.minio.access-key=${IGRP_STORAGE_ACCESS_KEY}
igrp.minio.secret-key=${IGRP_STORAGE_SECRET_KEY}
igrp.minio.bucket-name=${IGRP_STORAGE_BUCKET_NAME:igrp}
igrp.minio.url-expiration-time=${IGRP_STORAGE_PRESIGNED_URL_EXPIRATION_TIME:300}
igrp.minio.region=${IGRP_STORAGE_REGION:us-east-1}
igrp.s3.aws-endpoint=http://${IGRP_STORAGE_ENDPOINT}:${IGRP_STORAGE_PORT}
igrp.s3.aws-access-key=${IGRP_STORAGE_ACCESS_KEY}
igrp.s3.aws-secret-key=${IGRP_STORAGE_SECRET_KEY}
igrp.s3.secure=${IGRP_STORAGE_SECURITY}
igrp.s3.aws-bucket=${IGRP_STORAGE_BUCKET_NAME:igrp}
igrp.s3.aws-url-expiration-time=${IGRP_STORAGE_PRESIGNED_URL_EXPIRATION_TIME:300}
igrp.s3.aws-region=${IGRP_STORAGE_REGION:us-east-1}
igrp.s3.aws-path-style-access=${IGRP_STORAGE_PATH_STYLE_ACCESS:true}
# File manager Logging - Minio/S3
logging.level.io.minio=DEBUG
logging.level.io.awss3=DEBUG
logging.level.cv.igrp.platform.filemanager=DEBUG

# Authentication
igrp.keycloak.server-url=${IGRP_KEYCLOAK_SERVER_URL}
igrp.keycloak.realm=${IGRP_KEYCLOAK_REALM}
igrp.keycloak.client-id=${IGRP_KEYCLOAK_CLIENT_ID}
igrp.keycloak.client-secret=${IGRP_KEYCLOAK_CLIENT_SECRET}
igrp.keycloak.grant-type=${IGRP_KEYCLOAK_GRANT_TYPE:client_credentials}

spring.cache.type=redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}

# SMTP
igrp.notifications.enabled=${IGRP_NOTIFICATIONS_ENABLED:none}
igrp.mail.host=${SMTP_HOST:disabled}
igrp.mail.port=${SMTP_PORT:587}
igrp.mail.username=${SMTP_USERNAME:disabled}
igrp.mail.password=${SMTP_PASSWORD:disabled}
igrp.mail.properties.sender-id=${SMTP_SENDER_ID:iam@igrp.cv}

igrp.mail.invite.template=${IGRP_MAIL_INVITE_TEMPLATE:Hello {{user}}, you were successfully invited to iGRP! Please click on the link below to accept the invitation: {{url}} }
igrp.mail.invite.response.template=${IGRP_MAIL_INVITE_RESPONSE_TEMPLATE:Hello {{user}}, you accepted the invite to the iGRP platform successfully. You can now login using your email and password.}
igrp.mail.invite.cancellation.template=${IGRP_MAIL_INVITE_CANCELLATION_TEMPLATE:Hello {{user}}, your invitation to the iGRP platform was cancelled. If you have any questions, please contact the administrator.}

igrp.superadmin.user-external-id=${IGRP_SUPERADMIN_USER_EXTERNAL_ID}
igrp.superadmin.email=${IGRP_SUPERADMIN_EMAIL:superadmin@igrp.cv}

# Observability
otel.resource.attributes.service.name=${spring.application.name}
otel.resource.attributes.deployment.environment=${SPRING_PROFILES_ACTIVE:development}
otel.logs.exporter=otlp
otel.metrics.exporter=otlp
otel.traces.exporter=otlp
otel.exporter.otlp.endpoint=${OTEL_COLLECTOR_ENDPOINT}
otel.sdk.disabled=${OTEL_DISABLED:true}

# User Invitation
igrp.app-center.url=${IGRP_APP_CENTER_URL}